/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignatureRouteImport } from './routes/signature'
import { Route as RestaurantsRouteImport } from './routes/restaurants'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as DealsRouteImport } from './routes/deals'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as RSlugRouteImport } from './routes/r.$slug'
import { Route as PartnerMembershipRouteImport } from './routes/partner.membership'
import { Route as CuisinesSlugRouteImport } from './routes/cuisines.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as BlogCategorySlugRouteImport } from './routes/blog.category.$slug'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicCronExpireMembershipsRouteImport } from './routes/api/public/cron/expire-memberships'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignatureRoute = SignatureRouteImport.update({
  id: '/signature',
  path: '/signature',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantsRoute = RestaurantsRouteImport.update({
  id: '/restaurants',
  path: '/restaurants',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsRoute = DealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const RSlugRoute = RSlugRouteImport.update({
  id: '/r/$slug',
  path: '/r/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerMembershipRoute = PartnerMembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => PartnerRoute,
} as any)
const CuisinesSlugRoute = CuisinesSlugRouteImport.update({
  id: '/cuisines/$slug',
  path: '/cuisines/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogCategorySlugRoute = BlogCategorySlugRouteImport.update({
  id: '/blog/category/$slug',
  path: '/blog/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronExpireMembershipsRoute =
  ApiPublicCronExpireMembershipsRouteImport.update({
    id: '/api/public/cron/expire-memberships',
    path: '/api/public/cron/expire-memberships',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/deals': typeof DealsRoute
  '/membership': typeof MembershipRoute
  '/partner': typeof PartnerRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/restaurants': typeof RestaurantsRoute
  '/signature': typeof SignatureRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/cuisines/$slug': typeof CuisinesSlugRoute
  '/partner/membership': typeof PartnerMembershipRoute
  '/r/$slug': typeof RSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/blog/category/$slug': typeof BlogCategorySlugRoute
  '/api/public/cron/expire-memberships': typeof ApiPublicCronExpireMembershipsRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/deals': typeof DealsRoute
  '/membership': typeof MembershipRoute
  '/partner': typeof PartnerRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/restaurants': typeof RestaurantsRoute
  '/signature': typeof SignatureRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/cuisines/$slug': typeof CuisinesSlugRoute
  '/partner/membership': typeof PartnerMembershipRoute
  '/r/$slug': typeof RSlugRoute
  '/blog': typeof BlogIndexRoute
  '/blog/category/$slug': typeof BlogCategorySlugRoute
  '/api/public/cron/expire-memberships': typeof ApiPublicCronExpireMembershipsRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/deals': typeof DealsRoute
  '/membership': typeof MembershipRoute
  '/partner': typeof PartnerRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/restaurants': typeof RestaurantsRoute
  '/signature': typeof SignatureRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/cuisines/$slug': typeof CuisinesSlugRoute
  '/partner/membership': typeof PartnerMembershipRoute
  '/r/$slug': typeof RSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/blog/category/$slug': typeof BlogCategorySlugRoute
  '/api/public/cron/expire-memberships': typeof ApiPublicCronExpireMembershipsRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/deals'
    | '/membership'
    | '/partner'
    | '/privacy'
    | '/reset-password'
    | '/restaurants'
    | '/signature'
    | '/terms'
    | '/blog/$slug'
    | '/cuisines/$slug'
    | '/partner/membership'
    | '/r/$slug'
    | '/blog/'
    | '/blog/category/$slug'
    | '/api/public/cron/expire-memberships'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/deals'
    | '/membership'
    | '/partner'
    | '/privacy'
    | '/reset-password'
    | '/restaurants'
    | '/signature'
    | '/terms'
    | '/blog/$slug'
    | '/cuisines/$slug'
    | '/partner/membership'
    | '/r/$slug'
    | '/blog'
    | '/blog/category/$slug'
    | '/api/public/cron/expire-memberships'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/deals'
    | '/membership'
    | '/partner'
    | '/privacy'
    | '/reset-password'
    | '/restaurants'
    | '/signature'
    | '/terms'
    | '/blog/$slug'
    | '/cuisines/$slug'
    | '/partner/membership'
    | '/r/$slug'
    | '/blog/'
    | '/blog/category/$slug'
    | '/api/public/cron/expire-memberships'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  DealsRoute: typeof DealsRoute
  MembershipRoute: typeof MembershipRoute
  PartnerRoute: typeof PartnerRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RestaurantsRoute: typeof RestaurantsRoute
  SignatureRoute: typeof SignatureRoute
  TermsRoute: typeof TermsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CuisinesSlugRoute: typeof CuisinesSlugRoute
  RSlugRoute: typeof RSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  BlogCategorySlugRoute: typeof BlogCategorySlugRoute
  ApiPublicCronExpireMembershipsRoute: typeof ApiPublicCronExpireMembershipsRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signature': {
      id: '/signature'
      path: '/signature'
      fullPath: '/signature'
      preLoaderRoute: typeof SignatureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants': {
      id: '/restaurants'
      path: '/restaurants'
      fullPath: '/restaurants'
      preLoaderRoute: typeof RestaurantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals': {
      id: '/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof DealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$slug': {
      id: '/r/$slug'
      path: '/r/$slug'
      fullPath: '/r/$slug'
      preLoaderRoute: typeof RSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/membership': {
      id: '/partner/membership'
      path: '/membership'
      fullPath: '/partner/membership'
      preLoaderRoute: typeof PartnerMembershipRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/cuisines/$slug': {
      id: '/cuisines/$slug'
      path: '/cuisines/$slug'
      fullPath: '/cuisines/$slug'
      preLoaderRoute: typeof CuisinesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/category/$slug': {
      id: '/blog/category/$slug'
      path: '/blog/category/$slug'
      fullPath: '/blog/category/$slug'
      preLoaderRoute: typeof BlogCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/expire-memberships': {
      id: '/api/public/cron/expire-memberships'
      path: '/api/public/cron/expire-memberships'
      fullPath: '/api/public/cron/expire-memberships'
      preLoaderRoute: typeof ApiPublicCronExpireMembershipsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PartnerRouteChildren {
  PartnerMembershipRoute: typeof PartnerMembershipRoute
}

const PartnerRouteChildren: PartnerRouteChildren = {
  PartnerMembershipRoute: PartnerMembershipRoute,
}

const PartnerRouteWithChildren =
  PartnerRoute._addFileChildren(PartnerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  DealsRoute: DealsRoute,
  MembershipRoute: MembershipRoute,
  PartnerRoute: PartnerRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RestaurantsRoute: RestaurantsRoute,
  SignatureRoute: SignatureRoute,
  TermsRoute: TermsRoute,
  BlogSlugRoute: BlogSlugRoute,
  CuisinesSlugRoute: CuisinesSlugRoute,
  RSlugRoute: RSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  BlogCategorySlugRoute: BlogCategorySlugRoute,
  ApiPublicCronExpireMembershipsRoute: ApiPublicCronExpireMembershipsRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
